### ISSUE TITLE
Repo URL is a stale link

### ISSUE THREAD

**Issue by bbaassssiiee** [Thulium-Drake/ansible-collection-general#1]
Hi,

I noticed the [Repo]() link on https://galaxy.ansible.com/ui/repo/published/thulium_drake/general/
is stale. It should be: [https://github.com/Thulium-Drake/ansible-collection-general](https://github.com/Thulium-Drake/ansible-collection-general)

In this file: 
https://github.com/Thulium-Drake/ansible-collection-general/blob/14edd7e0718b4b9c91fa2e5bcd3e7ec4c7662405/galaxy.yml#L11

**Comment by Thulium-Drake** [comment]
Oh durr, I seem to have missed that part when making this repo :sweat_smile: 

Also, this repo only contains the scripting I use to make the collection and publish it on Galaxy. The content itself is on their own repos on my profile :-)
